# Copyright 2026 CloudPirates GmbH & Co. KG
#
# Based on original work by CloudPirates GmbH & Co. KG
# Modified by Cisco Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: redis
description: An open source, in-memory data structure store used as a database, cache, and message broker.
type: application
version: 0.20.6
appVersion: "7.2.0"
keywords:
  - redis
  - database
  - cache
  - in-memory
  - key-value
  - nosql
home: https://www.redis.io
sources:
  - https://github.com/cisco-ai-defense/ai-defense-hybrid/tree/main/charts/redis
icon: https://a.storyblok.com/f/143071/512x512/32c74816d1/redis-logo.svg
annotations:
  license: Apache-2.0